spring.application.name=backend
spring.datasource.url=jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.lgzxbprtnbzjrpiyaczi
spring.datasource.password=Vivek@79854
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
jwt.secret=mySuperSecretKeyForJobPortalApplication2026ChangeThisInProduction
jwt.expiration=86400000